# Generated by Django 4.2.13 on 2024-05-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("batman", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="all_chai",
            name="image",
            field=models.ImageField(upload_to="batman/"),
        ),
    ]
